on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: authregdevdiv.azurecr.io
        username: ${{ secrets.acr_authregdevdiv_username }}
        password: ${{ secrets.acr_authregdevdiv_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t authregdevdiv.azurecr.io/test:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push authregdevdiv.azurecr.io/test:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_test_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep test958b | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace test958b`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: test958b
        container-registry-url: authregdevdiv.azurecr.io
        container-registry-username: ${{ secrets.acr_authregdevdiv_username }}
        container-registry-password: ${{ secrets.acr_authregdevdiv_password }}
        secret-name: testdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: test958b
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
          manifests/ingress-1.yml
        images: |
          authregdevdiv.azurecr.io/test:${{ github.sha }}
        imagepullsecrets: |
          testdockerauth
